stages:
  - validate
  - build


validate:
  stage: validate
  environment:
    name: test
  script:
    - packer --version
    - ansible --version
    - packer validate vsphere.pkr.hcl

build:
  stage: build
  environment:
    name: test
  tags:
    - local
  script:
    - pwd
    - packer build -force vsphere.pkr.hcl

build-rename:
  stage: build
  environment:
    name: test
  tags:
    - local
  script:
    - ansible-playbook template-rename.yml