stages:
  - validate
  - build
  - reorganize
  - production

IaC:
  stage: validate
  only:
    - test  
  environment:
    name: test
  script:
    - packer --version
    - ansible --version
    - packer validate vsphere.pkr.hcl
    - ansible-playbook default-config.yml --syntax-check
    - ansible-playbook template-rename.yml --syntax-check 
#  rules:
#    - exists:
#        - vsphere.pkr.hcl
#        - template-rename.yml

create-template:
  environment:
    name: test
  stage: build
  only:
    - test   
  tags:
    - local
  script:
    - packer build vsphere.pkr.hcl
#  needs:
#    - IaC

reorganize-templates:
  environment:
    name: test
  stage: reorganize
  only:
    - test 
  tags:
    - local
  script:
    - pip install Pyvmomi
    - ansible-playbook template-rename.yml
#  needs:
#    - create-template


build:
  stage: production
  environment:
    name: production
  only:
    - prod
  tags:
    - prod
  script:
    - packer build vsphere.pkr.hcl

apply:
  stage: production
  only:
    - prod
  tags: 
    - prod
  environment:
    name: production
  script:
    - pip3 install Pyvmomi
    - ansible-playbook template-rename.yml
  when: manual
