stages:
  - validate
  - build

IaC:
  stage: validate
  script:
    - packer --version
    - ansible --version
    - packer validate vsphere.pkr.hcl
    - ansible-playbook template-rename.yml --syntax-check 
  rules:
    - exists:
        - vsphere.pkr.hcl
        - template-rename.yml

template:
  stage: build
  tags:
    - local
  script:
    - packer build -force vsphere.pkr.hcl


rename:
  stage: build
  tags:
    - local
  script:
    - ansible-playbook template-rename.yml