---

- hosts: all
  become: true
  gather_facts: no
  vars_files:
    - input.yml

  tasks:
#    - name: Patching
#      yum:
#        name: '*'
#        state: latest
#       when: update == "yes"

    - name: Add admin group
      group:
        name: admin
        state: present

    - name: Creating local user
      user:
        name: dandy
        groups: admin
        comment: "1 of admins users"


    - name: Creating local user
      user:
        name: Ronaldo
        groups: admin
        comment: "1 of admins users"


    - name: Creating local user
      user:
        name: Super
        groups: admin
        comment: "1 of admins users"