---

- hosts: all
  become: true
  gather_facts: no
  vars_files:
    - input.yml

  tasks:
 #   - set_fact:
 #       update1: "yes"

    - name: Update OS
      yum:
        name: '*'
        state: latest

    - name: Create groups
      ansible.builtin.group:
        name: "{{ item.name }}"
        state: present
      with_items: "{{ groups_to_be_created }}"
  
    - name: Create local Users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        shell:  "{{ item.shell }}"
        comment: "{{ item.comment }}"
        password: "{{ 'Password1' | password_hash('sha512') }}"
        update_password: on_create
        append: yes
      with_items: "{{ users_to_be_created }}"


    - name: Ensure chrony package is installed
      ansible.builtin.dnf:
        name: chrony
        state: latest

    - name: Copy chrony config
      ansible.builtin.copy:
        src: chrony
        dest: /etc/chrony.conf
        mode: 644
        owner: root
        group: root
    
    - name: Enable & start chrony
      ansible.builtin.systemd:
        name: chronyd
        state: started
        enabled: yes
        masked: no