---
- name: Rename virtual machine from old name to new name using UUID
  gather_facts: yes
  vars_files:
    - input.yml
  vars:
#    vcenter: "{{ lookup('env','VCENTER') }}"
    vc_user: "{{ lookup('env','VC_USER') }}"
    vc_passwd: "{{ lookup('env','VC_PASSWD') }}"
    vm_name: "{{ lookup('env','ANS_VM_NAME') }}"
    datacenter: "{{ lookup('env','PKR_VAR_VC_DC') }}"
    cluster_name: "{{ lookup('env','PKR_VAR_VC_CLUSTER') }}"
    vcenter: "{{ lookup('env','PKR_VAR_VC_VCENTER') }}"
    template_name: "{{ lookup('env','ANS_TEMP_NAME') }}"
#    old: "{{ lookup('env','OLD_TEMPLATE') }}"
#    template_name: "TMP-CentOS8"
  hosts: localhost
  tasks:
    - set_fact:
#        vm_name: "{{ vm_name }}"
        new_vm_name: "template-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"
#        datacenter: "{{ datacenter }}"
#        cluster_name: "{{ cluster_name }}"

    - name: Get Template "{{ template_name }}" uuid
      vmware_guest_facts:
        hostname: "vcsa-01.lab.com"
        username: "administrator@vsphere.local"
        password: "Password1!"
        validate_certs: False
        datacenter: "{{ datacenter }}"
        folder: "/{{datacenter}}/vm"
        name: "{{ template_name }}"
      register: vm_facts

    - name: Rename "{{ template_name }}" to "{{ new_vm_name }}"
      vmware_guest:
        hostname: "{{ vcenter }}"
        username: "{{ vc_user }}"
        password: "{{ vc_passwd }}"
        validate_certs: False
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster_name }}"
        uuid: "{{ vm_facts.instance.hw_product_uuid }}"
        name: "{{ new_vm_name }}"
        is_template: yes

##############Set new Template ##################
    - name: Get new Template "{{ vm_name }}" uuid
      vmware_guest_facts:
        hostname: "{{ vcenter }}"
        username: "{{ vc_user }}"
        password: "{{ vc_passwd }}"
        validate_certs: False
        datacenter: "{{ datacenter }}"
        folder: "/{{datacenter}}/vm"
        name: "{{ vm_name }}"
      register: vm_facts

    - name: Rename "{{ vm_name }}" to "{{ template_name }}"
      vmware_guest:
        hostname: "{{ vcenter }}"
        username: "{{ vc_user }}"
        password: "{{ vc_passwd }}"
        validate_certs: False
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster_name }}"
        uuid: "{{ vm_facts.instance.hw_product_uuid }}"
        name: "{{ template_name }}"
        is_template: yes